language: php

php:
  - 7.0
  - 7.1

sudo: false

install:
  - composer require satooshi/php-coveralls:dev-master phpstan/phpstan
  - composer install

script:
  - phpunit --coverage-text --coverage-clover coverage.xml
  - vendor/bin/phpstan analyze -l 4 --no-progress src

after_script:
  - php vendor/bin/coveralls -v