language: php

php:
  - 7.0
  - 7.1

sudo: false

install:
  - composer require satooshi/php-coveralls:dev-master
  - composer install

script:
  - phpunit --coverage-text --coverage-clover coverage.xml

after_script:
  - php vendor/bin/coveralls -v